services:
  api:
    container_name: soundrush-api
    build:
      context: .
      dockerfile: go.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    environment:
      - DATABASE_URL=
volumes:
  db-data:
