services:
  app:
    container_name: soundrush-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7654:7654"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis # добавлено
    environment:
      DATABASE_URL: postgres://GGllc:soundrushpassword@db:5432/soundrush_production
      REDIS_URL: redis://redis:6379 # добавлено

  api:
    container_name: soundrush-api
    build:
      context: .
      dockerfile: go.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis # добавлено
    environment:
      - DATABASE_URL=postgres://GGllc:soundrushpassword@db:5432/soundrush_production
      - REDIS_URL=redis://redis:6379 # добавлено

  db:
    image: postgres
    environment:
      POSTGRES_USER: GGllc
      POSTGRES_PASSWORD: soundrushpassword
      POSTGRES_DB: soundrush_production
    volumes:
      - db-data:/var/lib/postgresql/data/

  redis: # новый сервис
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    restart: always

volumes:
  db-data: